### PR TITLE
This is an attempt to simplify the bin computation, based on the suggestion by Clayton Lewis at the Code Sprint. Testing (and, if possible, improvements) requested.

### PR DESCRIPTION
**Pull request by jasonjgw**

### CODE REVIEW

**Review by shepazu — CHANGES_REQUESTED** [review]
The one-liner for binning (to replace the `if…then` block) is elegant and works well in a local test. 

The `++max` line in `find_min_max_values` doesn't seem to be necessary, and it also throws an error in strict mode, since it's an undeclared variable. Even changing it to `++this.max` doesn't seem to affect the output. Please explain how it's necessary, or remove it.

Either way, I'll approve this PR once that isssue's resolved. It's elegant and more flexible than what I had.

**Comment by jasonjgw** [comment]
I agree this is the one issue that needs to be resolved before merging the pull request. Suppose min=0, max=100, interval=25, and one of the data values is 100. By the calculation, we have (100-0)/25 = 4. However, we need to ensure the result is in the range 0-3. I am open to whatever you take to be the best solution here.

**Comment by jasonjgw** [comment]
Before concluding for the night, I attempted an as yet untested solution. At least it should give a suggested way forward (even if it isn't right, which it probably isn't).

**Comment by shepazu** [comment]
Ah, you're right. I just tested it with this array: `0, 25, 50, 75, 100`.

As you explained, it did add a new bin.

Your method of increasing the max seems sound, and maybe we can work it into the line below?
`this.max = this.max % 2 == 0 ? this.max + 2 : this.max + 1;`

In testing this, though, I noticed that the value `0` is actually placed in bin 1, rather than bin 0. Any thoughts on how to solve that?

**Review by shepazu — APPROVED** [review]

**Pull request merged**
